/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2aeab5ee10c8d9d20e2958ba2d5d2319)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SYNCED_STATE_SERVER: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	GAME_ROOM: DurableObjectNamespace<import("./src/worker").GameRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SyncedStateServer" | "GameRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
